name: Build Docker Image

on:
  push:
    branches:
      - main

env:
  # 设置 docker 镜像名
  IMAGE_NAME: test

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.16.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
   
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.5.2
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Dependencies
      run: npm i -g yarn && yarn
      
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.5.0
      with:
        version: v0.3.0
        
    - name: Build Docker Image
      run: bash test/hello-bash.sh
      
      # 登录到 dockerhub，使用 GitHub secrets 传入账号密码，密码被加密存储在 GitHub 服务器，添加方法见下图。
    - name: Log into registry
      run: echo "${{ secrets.DOCKER_USERNAME }}" | docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

    - name: Push image
      run: |
          # 拼接镜像 id，这个镜像 id 就是在使用 docker 镜像时 pull 后面的名字。
          IMAGE_ID=capxh73/$IMAGE_NAME

          # 将所有的大写字母转为小写
          # IMAGE_ID=$(echo test | tr '[A-Z]' '[a-z]')

          # 从 GitHub.ref 中取出版本
          # VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # 从 tag 名字中替换 v 字符
          # [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          # [ "$VERSION" == "main" ] && VERSION=latest

          # echo IMAGE_ID=$IMAGE_ID
          # echo VERSION=$VERSION
          # 设置镜像 id 和版本号
          docker tag $IMAGE_NAME 
          # $IMAGE_ID:$VERSION
          # 进行 push
          docker push $IMAGE_NAME
          # $IMAGE_ID:$VERSION
